### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by antoniodeluca** [scientilla/scientilla#2]
Hi to all,

the main website (http://www.scientilla.net) seems to describe different features from those in this codebase and there is no information on GitHub about this new version of the project. 
Which are the goals for the current version of the project? 

The new repository does not specify any information about the license under which the code is distributed.
Could you clarify the license under which this new project is released?

Thanks for the help

**Comment by scientilla** [comment]
The scope and goals of the project will soon be published in the new project website, scientilla.org.

The licence for the project has just been added. We distribute our code under a MIT licence.

**Comment by antoniodeluca** [comment]
Ok, thanks.
