### ISSUE TITLE
All download links are 404s

### ISSUE THREAD

**Issue by giacecco** [scientilla/scientilla#4]
Hi All, is the project alive? All the download links at http://www.scientilla.org/ are 404s. Thanks.

**Comment by federicobozzini** [comment]
Hi, the project is alive and actively developed.

To try it out at the moment the only way would be to download the software from the git sources and follow the procedure shown in [the readme](https://github.com/scientilla/scientilla/blob/master/README.md) of the project.

In a very few weeks we will reach version 1 and the next steps will be to create both the official installation packages and a public demo where it's possible to register and  try Scientilla.

The download links on the project website referred to old versions of the Scientilla and I just removed them.

Sorry for any possible confusion.

**Comment by giacecco** [comment]
Thanks @iit-federico-bozzini , I will come back when version 1.0 is out. Have you got a distribution list for news?
